---
langs: [fr_FR]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation du plugin YamahaMusiccast"
description: "Le plugin YamahaMusiccast permet de dialoguer avec les appareils Yamaha compatibles musiccast."
author: "Luc Guinchard"
image: https://avatars3.githubusercontent.com/u/17431299?s=400&v=4
social:
  name: Luc Guinchard
  links:
    - https://github.com/lucguinchard
